# Generated by Django 4.2.1 on 2023-05-21 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_since',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Usuário desde'),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da remoçao do usuário'),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='user_since',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Usuário desde'),
        ),
        migrations.AlterField(
            model_name='useremailcheck',
            name='confirmed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da confimação'),
        ),
        migrations.AlterField(
            model_name='useremailcheck',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data do email'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da mensagem'),
        ),
    ]
