# Generated by Django 4.2.1 on 2023-05-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_useremailcheck_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailcheck',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da confimação'),
        ),
    ]
