# Generated by Django 4.2.1 on 2023-05-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_useremailcheck_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremailcheck',
            options={'ordering': ['-date']},
        ),
    ]
