# Generated by Django 4.2.1 on 2023-05-21 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_useremailcheck_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailcheck',
            name='confirmed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da confimação'),
        ),
    ]
