# Generated by Django 4.2.1 on 2023-05-21 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_useremailcheck_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_since',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Usuário desde'),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data da remoçao do usuário'),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='user_since',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Usuário desde'),
        ),
        migrations.AlterField(
            model_name='useremailcheck',
            name='confirmed',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data da confimação'),
        ),
        migrations.AlterField(
            model_name='useremailcheck',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data do email'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data da mensagem'),
        ),
    ]
