# Generated by Django 4.2.1 on 2023-05-21 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da criação'),
        ),
        migrations.AlterField(
            model_name='aboutuschanges',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Data da modificação'),
        ),
        migrations.AlterField(
            model_name='devpolicyacepted',
            name='acept_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da aceitação'),
        ),
        migrations.AlterField(
            model_name='devpolicychanges',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Data da modificação'),
        ),
        migrations.AlterField(
            model_name='devpolicyrules',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da criação'),
        ),
        migrations.AlterField(
            model_name='policyacepted',
            name='acept_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da aceitação'),
        ),
        migrations.AlterField(
            model_name='policychanges',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Data da modificação'),
        ),
        migrations.AlterField(
            model_name='policyrules',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da criação'),
        ),
    ]
